In [ ]:
import pandas as pd

data= pd.read_csv('SearchResults (1).csv', error_bad_lines=False)
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     1000 non-null   int64
 1   NCT Number               1000 non-null   object
 2   Title                    1000 non-null   object
 3   Acronym                  260 non-null    object
 4   Status                   1000 non-null   object
 5   Study Results            1000 non-null   object
 6   Conditions               998 non-null    object
 7   Interventions            921 non-null    object
 8   Outcome Measures         996 non-null    object
 9   Sponsor/Collaborators    1000 non-null   object
 10  Gender                   998 non-null    object
 11  Age                      998 non-null    object
 12  Phases                   761 non-null    object
 13  Enrollment               996 non-null    float64
 14  Funded Bys               998 non-null    object
 15  Study Type               998 non-null    object
 16  Study Designs            996 non-null    object
 17  Other IDs                998 non-null    object
 18  Start Date               996 non-null    object
 19  Primary Completion Date  996 non-null    object
 20  Completion Date          996 non-null    object
 21  First Posted             1000 non-null   object
 22  Results First Posted     0 non-null      float64
 23  Last Update Posted       1000 non-null   object
 24  Locations                730 non-null    object
 25  Study Documents          29 non-null     object
 26  URL                      1000 non-null   object
dtypes: float64(2), int64(1), object(24)
memory usage: 211.1+ KB

,Rank,NCT Number,Title,Acronym,Status,Study Results,Conditions,Interventions,Outcome Measures,Sponsor/Collaborators,...,Other IDs,Start Date,Primary Completion Date,Completion Date,First Posted,Results First Posted,Last Update Posted,Locations,Study Documents,URL
0,1,NCT05501834,Anxiety Surrounding Supracondylar Pin Removal ...,NaN,Not yet recruiting,No Results Available,Supracondylar Humerus Fracture|Anxiety,Other: Supracondylar Pin Removal Before Imaging,"Face, Legs, Activity, Cry and Consolability (F...",Boston Children's Hospital,...,IRB-P00039559,"September 1, 2022","September 1, 2023","January 1, 2024","August 15, 2022",NaN,"August 15, 2022",NaN,NaN,https://ClinicalTrials.gov/show/NCT05501834
1,2,NCT05501821,Study of KBA1412 in Participants With Advanced...,NaN,Recruiting,No Results Available,Advanced Solid Tumor Malignancy,Drug: KBA1412|Drug: Pembrolizumab,Part A & B & C: Frequency and severity of AEs ...,Kling Biotherapeutics B.V.,...,KBA1412-101,August 2022,January 2025,January 2025,"August 15, 2022",NaN,"August 15, 2022","University Hospital Ghent, Ghent, Belgium",NaN,https://ClinicalTrials.gov/show/NCT05501821
2,3,NCT05501808,Color Stability of Two Different Resin Matrix ...,NaN,Completed,No Results Available,Dental Restoration,Procedure: cerasmart|Procedure: enamic,color change|patient satisfaction,Fayoum University,...,COST 315,"June 1, 2021","June 1, 2022","August 1, 2022","August 15, 2022",NaN,"August 15, 2022","Faculty of Dentistry- Fayoum University, Fayou...",NaN,https://ClinicalTrials.gov/show/NCT05501808
3,4,NCT05501795,The Accuracy of Flap Thickness Versus the Pre-...,NaN,Recruiting,No Results Available,Myopia,Device: WaveLight® FS200 femtosecond laser,The resultant thickness of the FS200 created L...,Stephen Wexler|Sengi|Bismarck Lasik,...,SW-22-001,"August 9, 2022",August 2023,August 2023,"August 15, 2022",NaN,"August 15, 2022","Bismarck Lasik, Bismarck, North Dakota, United...",NaN,https://ClinicalTrials.gov/show/NCT05501795
4,5,NCT05501782,Evaluation of Intuitive Eating and Hedonic Hun...,NaN,Not yet recruiting,No Results Available,INTUITIVE EATING|Hedonic Hunger,Other: questionnaire,Intuitive eating scale (IES-2)|Power of food s...,Istanbul Medeniyet University,...,2022/0145,"September 1, 2022","December 1, 2022","December 1, 2022","August 15, 2022",NaN,"August 15, 2022",NaN,NaN,https://ClinicalTrials.gov/show/NCT05501782

In [13]:
#Supprimer les colonnes vides : Results First Posted & Study Documents
data.drop(['Results First Posted', 'Study Documents'],axis=1, inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     1000 non-null   int64
 1   NCT Number               1000 non-null   object
 2   Title                    1000 non-null   object
 3   Acronym                  260 non-null    object
 4   Status                   1000 non-null   object
 5   Study Results            1000 non-null   object
 6   Conditions               998 non-null    object
 7   Interventions            921 non-null    object
 8   Outcome Measures         996 non-null    object
 9   Sponsor/Collaborators    1000 non-null   object
 10  Gender                   998 non-null    object
 11  Age                      998 non-null    object
 12  Phases                   761 non-null    object
 13  Enrollment               996 non-null    float64
 14  Funded Bys               998 non-null    object
 15  Study Type               998 non-null    object
 16  Study Designs            996 non-null    object
 17  Other IDs                998 non-null    object
 18  Start Date               996 non-null    object
 19  Primary Completion Date  996 non-null    object
 20  Completion Date          996 non-null    object
 21  First Posted             1000 non-null   object
 22  Last Update Posted       1000 non-null   object
 23  Locations                730 non-null    object
 24  URL                      1000 non-null   object
dtypes: float64(1), int64(1), object(23)
memory usage: 235.4+ KB

In [17]:
#Data cleaning for float/int Data

#"max" function
def replace_max(x):
    data[x]=data[x].fillna(data[x].max())        
    data.info()

In [18]:
replace_max("Enrollment")

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     1000 non-null   int64
 1   NCT Number               1000 non-null   object
 2   Title                    1000 non-null   object
 3   Acronym                  260 non-null    object
 4   Status                   1000 non-null   object
 5   Study Results            1000 non-null   object
 6   Conditions               998 non-null    object
 7   Interventions            921 non-null    object
 8   Outcome Measures         996 non-null    object
 9   Sponsor/Collaborators    1000 non-null   object
 10  Gender                   998 non-null    object
 11  Age                      998 non-null    object
 12  Phases                   761 non-null    object
 13  Enrollment               1000 non-null   float64
 14  Funded Bys               998 non-null    object
 15  Study Type               998 non-null    object
 16  Study Designs            996 non-null    object
 17  Other IDs                998 non-null    object
 18  Start Date               996 non-null    object
 19  Primary Completion Date  996 non-null    object
 20  Completion Date          996 non-null    object
 21  First Posted             1000 non-null   object
 22  Last Update Posted       1000 non-null   object
 23  Locations                730 non-null    object
 24  URL                      1000 non-null   object
dtypes: float64(1), int64(1), object(23)
memory usage: 235.4+ KB

In [ ]:
def replace_min(x):
    data[x]=data[x].fillna(data[x].min())        
    data.info()

In [ ]:
def replace_max(x):
    data[x]=data[x].fillna(data[x].max())        
    data.info()

In [ ]:
def replace_mean(x):
    data[x]=data[x].fillna(data[x].mean())        
    data.info()

In [ ]:
def replace_constat(x):
    data[x]=data[x].fillna(value='x')
    data.info()

In [ ]:
def drop(x):
    data[x]=data[x].fillna(data[x].dropna)

In [ ]:
def